[versions]
android-gradle-plugin = "8.5.2"
kotlin = "1.9.24"
hilt = "2.52"
ksp = "1.9.24-1.0.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
